name: Node.js CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          npm i
          cd frontend
          npm i
          npm run build
          cd ..
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
